config/routes.rb
Rails.application.routes.draw do
  resources :burgers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/burger.rb
class Burger < ApplicationRecord
    #Call openfoodfacts API
    def nutriments
        code = self.code
        @product = Openfoodfacts::Product.get(code, locale: 'fr')
        if(@product) 
            @nutriments = @product.nutriments
            #p @nutriments
            @resultset = [
                "salt" => @nutriments.salt,
                "salt_unit" => @nutriments.salt_unit, 
                "sugars" => @nutriments.sugars,
                "sugars_unit" => @nutriments.sugars_unit,
                "proteins" => @nutriments.proteins,
                "proteins_unit" => @nutriments.proteins_unit,
                "sodium" => @nutriments.sodium,
                "sodium_unit" => @nutriments.sodium_unit,
                'energy' => @nutriments.energy,
                'energy_unit' => @nutriments.energy_unit
            ]
        else
            @resultset = [
                "salt" => "",
                "salt_unit" => "", 
                "sugars" => "",
                "sugars_unit" => "",
                "proteins" => "",
                "proteins_unit" => "",
                "sodium" => "",
                "sodium_unit" => "",
                'energy' => "",
                'energy_unit' => "",
            ]
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/burgers_controller.rb
class BurgersController < ApplicationController
  before_action :set_burger, only: [:show, :edit, :update, :destroy]

  # GET /burgers
  # GET /burgers.json
  def index
    @burgers = Burger.all
  end

  # GET /burgers/1
  # GET /burgers/1.json
  def show
  end

  # GET /burgers/new
  def new
    @burger = Burger.new
  end

  # GET /burgers/1/edit
  def edit
  end

  # POST /burgers
  # POST /burgers.json
  def create
    @burger = Burger.new(burger_params)

    respond_to do |format|
      if @burger.save
        format.html { redirect_to @burger, notice: 'Burger was successfully created.' }
        format.json { render :show, status: :created, location: @burger }
      else
        format.html { render :new }
        format.json { render json: @burger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /burgers/1
  # PATCH/PUT /burgers/1.json
  def update
    respond_to do |format|
      if @burger.update(burger_params)
        format.html { redirect_to @burger, notice: 'Burger was successfully updated.' }
        format.json { render :show, status: :ok, location: @burger }
      else
        format.html { render :edit }
        format.json { render json: @burger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /burgers/1
  # DELETE /burgers/1.json
  def destroy
    @burger.destroy
    respond_to do |format|
      format.html { redirect_to burgers_url, notice: 'Burger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_burger
      @burger = Burger.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def burger_params
      params.require(:burger).permit(:name, :price, :image, :nutriscore, :code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/burgers_helper.rb
module BurgersHelper
end

app/views/burgers/_form.html.erb
<%= form_with(model: burger, local: true) do |form| %>
  <% if burger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(burger.errors.count, "error") %> prohibited this burger from being saved:</h2>

      <ul>
        <% burger.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :nutriscore %>
    <%= form.text_field :nutriscore %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/burgers/edit.html.erb
<h1>Editing Burger</h1>

<%= render 'form', burger: @burger %>

<%= link_to 'Show', @burger %> |
<%= link_to 'Back', burgers_path %>

app/views/burgers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Burgers</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Price</th>
      <th>Image</th>
      <th>Nutriscore</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @burgers.each do |burger| %>
      <tr>
        <td><%= burger.code %></td>
        <td><%= burger.name %></td>
        <td><%= burger.price %></td>
        <td><%= burger.image %></td>
        <td><%= burger.nutriscore %></td>
        <td><%= link_to 'Show', burger %></td>
        <td><%= link_to 'Edit', edit_burger_path(burger) %></td>
        <td><%= link_to 'Destroy', burger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Burger', new_burger_path %>

app/views/burgers/new.html.erb
<h1>New Burger</h1>

<%= render 'form', burger: @burger %>

<%= link_to 'Back', burgers_path %>

app/views/burgers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @burger.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @burger.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @burger.price %>
</p>

<p>
  <strong>Image:</strong>
  <%= @burger.image %>
</p>

<p>
  <strong>Nutriscore:</strong>
  <%= @burger.nutriscore %>
</p>

<p>
  <strong>Nutriments:</strong>
</p>
<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Quantité</th>
    </tr>
  </thead>

  <tbody>
    <% @burger.nutriments.each do |burger| %>
      <tr>
        <td>Salt</td>
        <td><%= burger["salt"] %> <%= burger["salt_unit"] %> </td>
      </tr>
      <td>Sugars</td>
      <td><%= burger["sugars"] %> <%= burger["sugars_unit"] %></td>
    <tr>
      <td>Proteins</td>
      <td><%= burger["proteins"] %> <%= burger["proteins_unit"] %></td>
    </tr>
    <tr>
      <td>Sodium</td>
      <td><%= burger["sodium"] %> <%= burger["sodium_unit"] %></td>
    </tr>
    <tr>
      <td>Energy</td>
      <td><%= burger["energy"] %> <%= burger["energy_unit"] %></td>
    </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_burger_path(@burger) %> |
<%= link_to 'Back', burgers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LPA2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>